# Generated by Django 5.2.1 on 2025-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConversionApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabelconfig",
            name="header_footer_left_width_margin",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="whitelabelconfig",
            name="header_footer_right_width_margin",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="whitelabelconfig",
            name="page_footer_height",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="whitelabelconfig",
            name="page_header_height",
            field=models.PositiveIntegerField(default=35),
        ),
    ]
